version: '3.8'

services:
  web:
    container_name: web
    build:
      dockerfile: Dockerfile
    volumes:
      - ./static:/app/staticfiles
    restart: on-failure
    ports:
      - 8000:8000
    environment:
      - DEBUG=False

  