name: 'Terraform Plan Apply'

on:
  # workflow_dispatch: -> за да го ръннем на ръка
  push:
    branches: [ "main" ]

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }} 
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  
jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
  
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Login to Azure using the secrets
    - name: Login to Azure  
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Generate terraform execution plan
    - name: Terraform Plan
      run: terraform plan -out=tfplan

    # Save terraform plan
    - name: Save Terraform Plan
      uses: actions/upload-artifact@v2
      with:
        name: tfplan
        path: tfplan


  terraform-plan-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    needs: [terraform-plan]
  
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Download the file
    - name: Download Terraform Plan
      uses: actions/download-artifact@v2
      with:
        name: tfplan # Name of the artifact you want to download

    # Terraform Apply
    - name: Apply the plan
      run: terraform apply -auto-approve tfplan